// LLM DTOs (v0.16a — corrected to match the Rust source of truth).
//
// These types are the wire-format mirror of:
//   src-tauri/src/commands/llm.rs::LlmAnalysisDto
//   src-tauri/src/commands/llm.rs::LlmRecommendationDto
//   src-tauri/src/commands/llm.rs::LlmCallLog (the relevant fields)
//
// The schema (src/db/schema/index.ts) uses `text('id')` for the
// primary key on `llm_analyses` (UUID generated by Rust with
// `Uuid::new_v4().to_string()`) but `integer` autoincrement for
// `llm_recommendations.id` and `llm_call_logs.id`. v0.15c had
// to `as unknown as number` cast the analysis id to work around
// this type mismatch; v0.16a fixes the type so the cast goes away.
//
// Naming: snake_case fields match the Rust DTOs. Tauri 2 IPC
// accepts snake_case args directly; for camelCase JSON to map
// to snake_case Rust, the `args` struct is used (and Tauri
// auto-converts).

export type ProviderKind =
  | 'openai'
  | 'anthropic'
  | 'google'
  | 'deepseek'
  | 'openai_compat'
  | 'anthropic_compat';

export interface LlmProvider {
  id: string;
  display_name: string;
  kind: ProviderKind;
  api_base: string | null;
  default_model: string;
  enabled: boolean;
  cost_per_1k_in: number | null;
  cost_per_1k_out: number | null;
  timeout_ms: number;
  max_retries: number;
  health_status: string | null;
  health_latency_p50_ms: number | null;
  last_health_check_at: number | null;
  last_health_error: string | null;
}

export interface LlmProviderKey {
  id: string;
  provider_id: string;
  alias: string;
  keyring_alias: string;
  priority: number;
  enabled: boolean;
  created_at: number;
  /** True if the OS keyring entry exists for this key. */
  has_secret: boolean;
}

export interface LlmCallLog {
  /** Auto-increment primary key on `llm_call_logs`. */
  id: number;
  provider_id: string;
  key_id: string | null;
  /** UUID string matching `llm_analyses.id`. Null for non-analyze
   * calls (e.g. `llm_test_connectivity`). */
  analysis_id: string | null;
  called_at: number;
  model_used: string;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  cost_cents: number;
  success: boolean;
  error_code: string | null;
  error_message: string | null;
  http_status: number | null;
  latency_ms: number | null;
}

export type ErrorCode =
  | 'auth'
  | 'rate_limit'
  | 'timeout'
  | 'network'
  | 'parse'
  | 'model_not_found'
  | 'quota'
  | 'unknown';

/**
 * Wire-format mirror of `LlmAnalysisDto` from the Rust side.
 *
 * v0.16a — `id` is a UUID string, NOT a number. The schema
 * defines `id: text('id').primaryKey()` and Rust generates
 * it with `Uuid::new_v4().to_string()`. The previous
 * `id: number` was a long-standing bug masked by an
 * `as unknown as number` cast at the call site.
 *
 * Field names match the Rust DTO exactly (snake_case).
 */
export interface LlmAnalysis {
  id: string;
  market_id: string;
  signal_id: number | null;
  prompt_version: string;
  requested_at: number;
  completed_at: number | null;
  status: 'pending' | 'completed' | 'partial' | 'failed';
  consensus_predicted: number | null;
  consensus_side: string | null;
  consensus_conf: number | null;
  total_latency_ms: number | null;
  cost_cents: number | null;
  triggered_by: string;
  recommendations: LlmRecommendation[];
}

/**
 * Wire-format mirror of `LlmRecommendationDto` from the Rust
 * side. `id` is auto-increment integer (per row); `analysis_id`
 * is the UUID string of the parent analysis.
 *
 * v0.16a — corrected from `analysis_id: number` to
 * `analysis_id: string`. Added `provider_name` (the resolved
 * display_name from `llm_providers` joined in the query).
 */
export interface LlmRecommendation {
  id: number;
  analysis_id: string;
  provider_id: string;
  provider_name: string;
  predicted_prob: number | null;
  side: string | null;
  confidence: number | null;
  reasoning: string | null;
  latency_ms: number | null;
  tokens_in: number | null;
  tokens_out: number | null;
  cost_cents: number | null;
  parse_ok: boolean;
  parse_error: string | null;
}

export interface LlmPerformance {
  model_version: string;
  n_predictions: number;
  win_rate: number;
  brier_score: number;
  log_loss: number;
  avg_edge: number;
}

export interface LlmHeatmapCell {
  model_version: string;
  prompt_version: string;
  n: number;
  win_rate: number;
  brier: number;
}

export interface LlmScatterPoint {
  analysis_id: number;
  market_id: string;
  predicted_prob: number;
  market_prob: number;
  outcome: number | null;
  resolved_at: number | null;
}

export interface LlmTimeseriesPoint {
  bucket_ts: number;
  n_calls: number;
  n_success: number;
  cost_cents: number;
  avg_latency_ms: number;
}

export interface ConnectivityTestResult {
  provider_id: string;
  key_id: string;
  ok: boolean;
  http_status: number | null;
  latency_ms: number;
  error_code: ErrorCode | null;
  error_message: string | null;
}

export interface LlmTrafficSummary {
  window_start: number;
  window_end: number;
  total_calls: number;
  success_calls: number;
  total_cost_cents: number;
  per_provider: Array<{
    provider_id: string;
    calls: number;
    cost_cents: number;
    avg_latency_ms: number;
  }>;
}

export interface UpsertLlmProviderArgs {
  id: string;
  display_name: string;
  kind: ProviderKind;
  api_base?: string;
  default_model: string;
  enabled?: boolean;
  cost_per_1k_in?: number;
  cost_per_1k_out?: number;
  timeout_ms?: number;
  max_retries?: number;
}

export interface UpsertLlmKeyArgs {
  provider_id: string;
  id?: string;
  alias: string;
  keyring_alias: string;
  priority?: number;
  enabled?: boolean;
  secret?: string;
}
